amcheck.bundle=amcheck.tar.gz
auto_explain.bundle=auto_explain.tar.gz
bloom.bundle=bloom.tar.gz
btree_gin.bundle=btree_gin.tar.gz
btree_gist.bundle=btree_gist.tar.gz
citext.bundle=citext.tar.gz
cube.bundle=cube.tar.gz
dict_int.bundle=dict_int.tar.gz
dict_xsyn.bundle=dict_xsyn.tar.gz
earthdistance.bundle=earthdistance.tar.gz
file_fdw.bundle=file_fdw.tar.gz
fuzzystrmatch.bundle=fuzzystrmatch.tar.gz
hstore.bundle=hstore.tar.gz
intarray.bundle=intarray.tar.gz
isn.bundle=isn.tar.gz
lo.bundle=lo.tar.gz
ltree.bundle=ltree.tar.gz
pageinspect.bundle=pageinspect.tar.gz
pg_buffercache.bundle=pg_buffercache.tar.gz
pg_freespacemap.bundle=pg_freespacemap.tar.gz
pg_stat_statements.bundle=pg_stat_statements.tar.gz
pg_stat_statements.sharedPreloadLibraries=pg_stat_statements
pg_surgery.bundle=pg_surgery.tar.gz
pg_trgm.bundle=pg_trgm.tar.gz
pg_visibility.bundle=pg_visibility.tar.gz
pg_walinspect.bundle=pg_walinspect.tar.gz
pgcrypto.bundle=pgcrypto.tar.gz
seg.bundle=seg.tar.gz
tablefunc.bundle=tablefunc.tar.gz
tcn.bundle=tcn.tar.gz
tsm_system_rows.bundle=tsm_system_rows.tar.gz
tsm_system_time.bundle=tsm_system_time.tar.gz
unaccent.bundle=unaccent.tar.gz
uuid_ossp.bundle=uuid-ossp.tar.gz
