diff --git a/src/backend/Makefile b/src/backend/Makefile
index 01f01bd734..92ef5d19f6 100644
--- a/src/backend/Makefile
+++ b/src/backend/Makefile
@@ -62,6 +62,7 @@ override LDFLAGS := $(LDFLAGS) $(LDFLAGS_EX) $(LDFLAGS_EX_BE)
 all: submake-libpgport submake-catalog-headers submake-utils-headers postgres $(POSTGRES_IMP)
 
 ifneq ($(PORTNAME), emscripten)
+ifneq ($(PORTNAME), wasi)
 ifneq ($(PORTNAME), cygwin)
 ifneq ($(PORTNAME), win32)
 
@@ -71,6 +72,7 @@ postgres: $(OBJS)
 endif
 endif
 endif
+endif
 
 ifeq ($(PORTNAME), emscripten)
 
@@ -110,6 +112,19 @@ pglite-libc:
 
 endif
 
+ifeq ($(PORTNAME), wasi)
+
+postgres: $(OBJS)
+	$(CC) $(CFLAGS) $(call expand_subsys,$^) $(LDFLAGS) $(LIBS) -o $@$(X)
+
+pglite-wasi: $(OBJS)
+	$(CC) $(CFLAGS) $(call expand_subsys,$^) $(POSTGRES_PGLITE_WASI_EXTRA_OBJS) $(top_builddir)/pglite/src/pglitec/initdb.o $(top_builddir)/pglite/src/pglitec/pqexpbuffer.o $(top_builddir)/pglite/src/pglitec/option_utils.o $(top_builddir)/pglite/src/pglitec/pglitec.o $(LDFLAGS) $(LIBS) $(POSTGRES_PGLITE_WASI_FLAGS) -o $@$(X)
+
+install-pglite-wasi:
+	$(INSTALL_PROGRAM) pglite-wasi$(X) '$(DESTDIR)$(bindir)/pglite.wasi.wasm'
+
+endif
+
 ifeq ($(PORTNAME), cygwin)
 
 postgres: $(OBJS)
@@ -137,6 +152,8 @@ endif # win32
 
 $(top_builddir)/src/port/libpgport_srv.a: | submake-libpgport
 
+$(top_builddir)/src/common/libpgcommon_srv.a: | submake-libpgport
+
 
 # The following targets are specified in make commands that appear in
 # the make files in our subdirectories. Note that it's important we
