// Auto-generated by tools/generateCustomRelease.mjs
import type { EmAsmHandler } from "../core/runtimeTypes.js";

export const emAsmRegistry: Record<number, EmAsmHandler> = {
	2537480: (context, fdBufferMax) => {
		const moduleAny = context.module as Record<string, unknown>;
		moduleAny.is_worker =
			typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope;
		moduleAny.FD_BUFFER_MAX = Number(fdBufferMax ?? 0);
		moduleAny.emscripten_copy_to = console.warn;
	},
	2537652: (context) => {
		context.module.postMessage = function custom_postMessage(event: unknown) {
			console.log("# pg_main_emsdk.c:544: onCustomMessage:", event);
		};
	},
	2537781: (context) => {
		const moduleAny = context.module as Record<string, unknown>;
		if (moduleAny.is_worker) {
			moduleAny.onCustomMessage = function onCustomMessage(event: unknown) {
				console.log("onCustomMessage:", event);
			};
			return;
		}
		context.module.postMessage = function custom_postMessage(event: unknown) {
			if (
				typeof event === "object" &&
				event !== null &&
				"type" in event &&
				"data" in event &&
				(event as { type: string }).type === "stdin"
			) {
				if (!context.stringToUTF8) {
					throw new Error("stringToUTF8 is required for stdin EM_ASM handler");
				}
				const data = String((event as { data: unknown }).data ?? "");
				const fdBufferMax = Number(moduleAny.FD_BUFFER_MAX ?? 0);
				context.stringToUTF8(data, 1, fdBufferMax);
				return;
			}
			if (
				typeof event === "object" &&
				event !== null &&
				"type" in event &&
				((event as { type: string }).type === "raw" ||
					(event as { type: string }).type === "rcon")
			) {
				return;
			}
			console.warn("custom_postMessage?", event);
		};
	},
};
