// Auto-generated by tools/generateCustomRelease.mjs
import type { EmJsHandler } from "../core/runtimeTypes.js";

export const emJsRegistry: Record<string, EmJsHandler> = {
	
};

export const emJsSymbolNames = [];
